### ISSUE TITLE
".iconx数字"、".icon*数字"が表示されない

### ISSUE THREAD

**Issue by napo0703** [Hikaru-Ito/Gyazz-App#22]
iOSです。
".icon"は問題ない。
http://gyazz.masuilab.org/増井研/test
表示されるものもあるけどなんかでかい。
![](http://i.gyazo.com/a59a4ca37b8309673251097f5086b62d.png)

**Comment by Hikaru-Ito** [comment]
なんか面白いｗ
これについてもできるだけ早く直します。
