### ISSUE TITLE
メニューバーをタップしたらページの最上部までスクロールしてほしい

### ISSUE THREAD

**Issue by napo0703** [Hikaru-Ito/Gyazz-App#23]
画面上端のメニューバーをタップしたらページの最上部までスクロールしてほしい。
iOS向けなのかな？

**Comment by Hikaru-Ito** [comment]
実装します。

**Comment by Hikaru-Ito** [comment]
ちなみに今のところ、ヘッダーのタイトルをタップすると最上部までスクロールされます。
ステータスバーのところは未実装でした。
