### ISSUE TITLE
スターをつけたページが更新されたら通知がきてほしい

### ISSUE THREAD

**Issue by masakyx** [Hikaru-Ito/Gyazz-App#27]

**Comment by shokai** [comment]
http://gyazz.masuilab.org/増井研/.通知
にURL書いておくと通知が来るので、それを適当なサーバーで受けて、push通知送ればよさげ

**Comment by Hikaru-Ito** [comment]
iOSは実装してリリースしました。(v1.3.1)

**Comment by Hikaru-Ito** [comment]
Androidもようやく実装してリリースした (v1.4.1)
